[phases.setup]
nixPkgs = ["...", "cron"]
aptPkgs = ["...", "nginx", "systemctl"] #nginx doesnt work well in nix for some reason

[phases.build]
cmds = [
  "...",
  "echo \"hewooooo :3\" > /app/content/hai.txt",
  "cat /app/content/hai.txt",
  ]

[start] 
cmd = "nginx -c /app/conf/nginx.conf && echo ${PORT} && tail -f /var/log/nginx/access.log /var/log/nginx/error.log"